# Merge Accidents and Nodes, then union with fixed camera locations\

### Import modules

In [1]:
import pandas
import datetime

### Set Paths

In [2]:
nodes_path = "/users/danielcorcoran/desktop/github_repos/tableau_projects/Vic Crash Stats (Extracted 4-5-2018)/raw data/NODES_DPC_2.csv"
accident_path = "/users/danielcorcoran/desktop/github_repos/tableau_projects/Vic Crash Stats (Extracted 4-5-2018)/raw data/ACCIDENT.csv"
camera_path = "/users/danielcorcoran/desktop/github_repos/tableau_projects/Vic Crash Stats (Extracted 4-5-2018)/raw data/Fixed Camera/fixed_camera_locations_with_lga.csv"

### Read in data

In [3]:
nodes_data = pandas.read_csv(nodes_path)

In [4]:
accident_data = pandas.read_csv(accident_path, low_memory=False)

In [5]:
camera_data = pandas.read_csv(camera_path)

### Preview Data

In [6]:
nodes_data.drop(["LONGITUDE","LATITUDE"], axis = 1, inplace = True)

In [7]:
nodes_data.head()

,NODE_ROW_INDEX,ACCIDENT_NO,NODE_ID,NODE_TYPE,AMG_X,AMG_Y,LGA_NAME,Lga Name All,Region Name,Deg Urban Name,...,Gindex,ROW_INDEX,ADDRESS_DETAIL_PID,POSTCODE,ADDRESS_SITE_PID,STREET_LOCALITY_PID,GNAF_PROPERTY_PID,ADDRESS_DEFAULT_GEOCODE_PID,STREET_NAME,STREET_TYPE_CODE
0,0,T20060000010,43078,I,2519154.655,2390265.154,DANDENONG,DANDENONG,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,...,748115.0,748115,GAVIC421916814,3175,422053715,VIC1958844,578458.0,1278932,FOSTER,STREET
1,1,T20060000018,29720,N,2524272.743,2389996.817,CASEY,CASEY,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,...,3316705.0,3316705,GAVIC423900268,3804,423990899,VIC2056738,208310432.0,4184146,WEST VISTA,PLACE
2,2,T20060000022,203074,N,2487321.693,2345019.925,MORNINGTON PENINSULA,MORNINGTON PENINSULA,METROPOLITAN SOUTH EAST REGION,RURAL_VICTORIA,...,69424.0,69424,GAVIC423134249,3939,423237624,VIC1930473,1040683.0,4406982,BROWNS,ROAD
3,3,T20060000023,55462,I,2512734.120,2390214.959,DANDENONG,"KINGSTON,DANDENONG",METROPOLITAN SOUTH EAST REGION,MELB_URBAN,...,1672264.0,1672264,GAVIC424971689,3173,425057037,VIC2070403,2544.0,2468987,SPRINGVALE,ROAD
4,4,T20060000026,202988,N,2488777.662,2347612.069,MORNINGTON PENINSULA,MORNINGTON PENINSULA,METROPOLITAN SOUTH EAST REGION,MELB_URBAN,...,3507205.0,3507205,GAVIC719219660,3940,714604693,VIC3619977,220275836.0,3007415064,ELIZABETH,AVENUE

In [8]:
nodes_data.shape

(163913, 29)

In [9]:
accident_data.head()

,ACCIDENT_ROW_INDEX,ACCIDENT_NO,ACCIDENTDATE,ACCIDENTTIME,ACCIDENT_TYPE,Accident Type Desc,DAY_OF_WEEK,Day Week Description,DCA_CODE,DCA Description,...,NO_PERSONS,NO_PERSONS_INJ_2,NO_PERSONS_INJ_3,NO_PERSONS_KILLED,NO_PERSONS_NOT_INJ,POLICE_ATTEND,ROAD_GEOMETRY,Road Geometry Desc,SEVERITY,SPEED_ZONE
0,0,T20060000010,13/1/06,12.42.00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),...,6,0,1,0,5,1,1,Cross intersection,3,60
1,1,T20060000018,13/1/06,19.10.00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),...,4,0,1,0,3,1,2,T intersection,3,70
2,2,T20060000022,14/1/06,12.10.00,7,Fall from or in moving vehicle,7,Saturday,190,FELL IN/FROM VEHICLE,...,2,1,0,0,1,1,5,Not at intersection,2,100
3,3,T20060000023,14/1/06,11.49.00,1,Collision with vehicle,7,Saturday,130,REAR END(VEHICLES IN SAME LANE),...,2,1,0,0,1,1,2,T intersection,2,80
4,4,T20060000026,14/1/06,10.45.00,1,Collision with vehicle,7,Saturday,121,RIGHT THROUGH,...,3,0,3,0,0,1,5,Not at intersection,3,50

In [10]:
accident_data.shape

(164789, 29)

In [11]:
camera_data.head()

,row_index,location_long,location_short,longitude,latitude,lga_code
0,0,Scoresby Road at the intersection of Scoresby ...,Bayswater,145.271051,-37.838904,23670
1,1,Blackshaws Road at the intersection of Blacksh...,Altona North,144.848075,-37.831187,23110
2,2,Warrigal Road at the intersection of Warrigal ...,Cheltenham,145.074250,-37.967517,23430
3,3,"Western Ring Road, Northbound Keilor Park Driv...",Western Ring Road Keilor East,144.850992,-37.738260,21180
4,4,"Western Ring Road, Northbound Western Highway ...",Western Ring Road Deer Park,144.793847,-37.774961,21180

In [12]:
camera_data_subset = camera_data[["location_long", "location_short", "longitude", "latitude", "lga_code"]]

camera_data_subset.head()

,location_long,location_short,longitude,latitude,lga_code
0,Scoresby Road at the intersection of Scoresby ...,Bayswater,145.271051,-37.838904,23670
1,Blackshaws Road at the intersection of Blacksh...,Altona North,144.848075,-37.831187,23110
2,Warrigal Road at the intersection of Warrigal ...,Cheltenham,145.074250,-37.967517,23430
3,"Western Ring Road, Northbound Keilor Park Driv...",Western Ring Road Keilor East,144.850992,-37.738260,21180
4,"Western Ring Road, Northbound Western Highway ...",Western Ring Road Deer Park,144.793847,-37.774961,21180

In [13]:
camera_data_subset.columns = ["camera_location_desc_long", "camera_location_desc_short", "Long", "Lat", "lga_code"]

In [14]:
camera_data_subset.head()

,camera_location_desc_long,camera_location_desc_short,Long,Lat,lga_code
0,Scoresby Road at the intersection of Scoresby ...,Bayswater,145.271051,-37.838904,23670
1,Blackshaws Road at the intersection of Blacksh...,Altona North,144.848075,-37.831187,23110
2,Warrigal Road at the intersection of Warrigal ...,Cheltenham,145.074250,-37.967517,23430
3,"Western Ring Road, Northbound Keilor Park Driv...",Western Ring Road Keilor East,144.850992,-37.738260,21180
4,"Western Ring Road, Northbound Western Highway ...",Western Ring Road Deer Park,144.793847,-37.774961,21180

### Merge Accident Data with Nodes data

In [15]:
accident_nodes = pandas.merge(left=accident_data, right = nodes_data, how= "left", on="ACCIDENT_NO")

In [16]:
accident_nodes.head()

,ACCIDENT_ROW_INDEX,ACCIDENT_NO,ACCIDENTDATE,ACCIDENTTIME,ACCIDENT_TYPE,Accident Type Desc,DAY_OF_WEEK,Day Week Description,DCA_CODE,DCA Description,...,Gindex,ROW_INDEX,ADDRESS_DETAIL_PID,POSTCODE,ADDRESS_SITE_PID,STREET_LOCALITY_PID,GNAF_PROPERTY_PID,ADDRESS_DEFAULT_GEOCODE_PID,STREET_NAME,STREET_TYPE_CODE
0,0,T20060000010,13/1/06,12.42.00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),...,748115.0,748115.0,GAVIC421916814,3175.0,422053715.0,VIC1958844,578458.0,1.278932e+06,FOSTER,STREET
1,1,T20060000018,13/1/06,19.10.00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),...,3316705.0,3316705.0,GAVIC423900268,3804.0,423990899.0,VIC2056738,208310432.0,4.184146e+06,WEST VISTA,PLACE
2,2,T20060000022,14/1/06,12.10.00,7,Fall from or in moving vehicle,7,Saturday,190,FELL IN/FROM VEHICLE,...,69424.0,69424.0,GAVIC423134249,3939.0,423237624.0,VIC1930473,1040683.0,4.406982e+06,BROWNS,ROAD
3,3,T20060000023,14/1/06,11.49.00,1,Collision with vehicle,7,Saturday,130,REAR END(VEHICLES IN SAME LANE),...,1672264.0,1672264.0,GAVIC424971689,3173.0,425057037.0,VIC2070403,2544.0,2.468987e+06,SPRINGVALE,ROAD
4,4,T20060000026,14/1/06,10.45.00,1,Collision with vehicle,7,Saturday,121,RIGHT THROUGH,...,3507205.0,3507205.0,GAVIC719219660,3940.0,714604693.0,VIC3619977,220275836.0,3.007415e+09,ELIZABETH,AVENUE

In [17]:
sorted(accident_nodes.columns)

['ACCIDENTDATE',
 'ACCIDENTTIME',
 'ACCIDENT_NO',
 'ACCIDENT_ROW_INDEX',
 'ACCIDENT_TYPE',
 'ADDRESS_DEFAULT_GEOCODE_PID',
 'ADDRESS_DETAIL_PID',
 'ADDRESS_SITE_PID',
 'AMG_X',
 'AMG_Y',
 'Accident Type Desc',
 'DAY_OF_WEEK',
 'DCA Description',
 'DCA_CODE',
 'DIRECTORY',
 'Day Week Description',
 'Deg Urban Name',
 'Distance',
 'EDITION',
 'GNAF_PROPERTY_PID',
 'GRID_REFERENCE_X',
 'GRID_REFERENCE_Y',
 'Gindex',
 'LGA_NAME',
 'LIGHT_CONDITION',
 'Lat',
 'Lga Name All',
 'Light Condition Desc',
 'Long',
 'NODE_ID_x',
 'NODE_ID_y',
 'NODE_ROW_INDEX',
 'NODE_TYPE',
 'NO_OF_VEHICLES',
 'NO_PERSONS',
 'NO_PERSONS_INJ_2',
 'NO_PERSONS_INJ_3',
 'NO_PERSONS_KILLED',
 'NO_PERSONS_NOT_INJ',
 'PAGE',
 'POLICE_ATTEND',
 'POSTCODE',
 'Postcode No',
 'ROAD_GEOMETRY',
 'ROW_INDEX',
 'Region Name',
 'Road Geometry Desc',
 'SEVERITY',
 'SPEED_ZONE',
 'STREET_LOCALITY_PID',
 'STREET_NAME',
 'STREET_TYPE_CODE',
 'lga_code',
 'lga_name',
 'node_row_index',
 'polygon_index',
 'script_results']

### Add columns to each dataset to identify whether its camera or crash data

In [18]:
accident_nodes["dataset_identifier"] = "Vic Crash Stats Data"
camera_data_subset["dataset_identifier"] = "Fixed Cameras Data"

In [19]:
accident_nodes.head()

,ACCIDENT_ROW_INDEX,ACCIDENT_NO,ACCIDENTDATE,ACCIDENTTIME,ACCIDENT_TYPE,Accident Type Desc,DAY_OF_WEEK,Day Week Description,DCA_CODE,DCA Description,...,ROW_INDEX,ADDRESS_DETAIL_PID,POSTCODE,ADDRESS_SITE_PID,STREET_LOCALITY_PID,GNAF_PROPERTY_PID,ADDRESS_DEFAULT_GEOCODE_PID,STREET_NAME,STREET_TYPE_CODE,dataset_identifier
0,0,T20060000010,13/1/06,12.42.00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),...,748115.0,GAVIC421916814,3175.0,422053715.0,VIC1958844,578458.0,1.278932e+06,FOSTER,STREET,Vic Crash Stats Data
1,1,T20060000018,13/1/06,19.10.00,1,Collision with vehicle,6,Friday,113,RIGHT NEAR (INTERSECTIONS ONLY),...,3316705.0,GAVIC423900268,3804.0,423990899.0,VIC2056738,208310432.0,4.184146e+06,WEST VISTA,PLACE,Vic Crash Stats Data
2,2,T20060000022,14/1/06,12.10.00,7,Fall from or in moving vehicle,7,Saturday,190,FELL IN/FROM VEHICLE,...,69424.0,GAVIC423134249,3939.0,423237624.0,VIC1930473,1040683.0,4.406982e+06,BROWNS,ROAD,Vic Crash Stats Data
3,3,T20060000023,14/1/06,11.49.00,1,Collision with vehicle,7,Saturday,130,REAR END(VEHICLES IN SAME LANE),...,1672264.0,GAVIC424971689,3173.0,425057037.0,VIC2070403,2544.0,2.468987e+06,SPRINGVALE,ROAD,Vic Crash Stats Data
4,4,T20060000026,14/1/06,10.45.00,1,Collision with vehicle,7,Saturday,121,RIGHT THROUGH,...,3507205.0,GAVIC719219660,3940.0,714604693.0,VIC3619977,220275836.0,3.007415e+09,ELIZABETH,AVENUE,Vic Crash Stats Data

In [20]:
camera_data_subset.head()

,camera_location_desc_long,camera_location_desc_short,Long,Lat,lga_code,dataset_identifier
0,Scoresby Road at the intersection of Scoresby ...,Bayswater,145.271051,-37.838904,23670,Fixed Cameras Data
1,Blackshaws Road at the intersection of Blacksh...,Altona North,144.848075,-37.831187,23110,Fixed Cameras Data
2,Warrigal Road at the intersection of Warrigal ...,Cheltenham,145.074250,-37.967517,23430,Fixed Cameras Data
3,"Western Ring Road, Northbound Keilor Park Driv...",Western Ring Road Keilor East,144.850992,-37.738260,21180,Fixed Cameras Data
4,"Western Ring Road, Northbound Western Highway ...",Western Ring Road Deer Park,144.793847,-37.774961,21180,Fixed Cameras Data

### Union vic crash data with fixed camera data

In [21]:
final_data = pandas.concat([accident_nodes, camera_data_subset] , axis = 0, sort = True)

In [22]:
final_data.shape

(165076, 60)

In [23]:
accident_nodes.shape

(164789, 58)

In [24]:
camera_data.shape

(287, 6)

In [25]:
accident_nodes.columns

Index(['ACCIDENT_ROW_INDEX', 'ACCIDENT_NO', 'ACCIDENTDATE', 'ACCIDENTTIME',
       'ACCIDENT_TYPE', 'Accident Type Desc', 'DAY_OF_WEEK',
       'Day Week Description', 'DCA_CODE', 'DCA Description', 'DIRECTORY',
       'EDITION', 'PAGE', 'GRID_REFERENCE_X', 'GRID_REFERENCE_Y',
       'LIGHT_CONDITION', 'Light Condition Desc', 'NODE_ID_x',
       'NO_OF_VEHICLES', 'NO_PERSONS', 'NO_PERSONS_INJ_2', 'NO_PERSONS_INJ_3',
       'NO_PERSONS_KILLED', 'NO_PERSONS_NOT_INJ', 'POLICE_ATTEND',
       'ROAD_GEOMETRY', 'Road Geometry Desc', 'SEVERITY', 'SPEED_ZONE',
       'NODE_ROW_INDEX', 'NODE_ID_y', 'NODE_TYPE', 'AMG_X', 'AMG_Y',
       'LGA_NAME', 'Lga Name All', 'Region Name', 'Deg Urban Name', 'Lat',
       'Long', 'Postcode No', 'node_row_index', 'polygon_index', 'lga_code',
       'lga_name', 'script_results', 'Distance', 'Gindex', 'ROW_INDEX',
       'ADDRESS_DETAIL_PID', 'POSTCODE', 'ADDRESS_SITE_PID',
       'STREET_LOCALITY_PID', 'GNAF_PROPERTY_PID',
       'ADDRESS_DEFAULT_GEOCODE_PID', 'STREET_NAME', 'STREET_TYPE_CODE',
       'dataset_identifier'],
      dtype='object')

### Drop Unnecessary columns

final_data.drop(["ACCIDENT_TYPE", 
                "DAY_OF_WEEK",
                "DCA_CODE",
                "LONGITUDE",
                "LATITUDE",
                "ADDRESS_SITE_PID",
                "ADDRESS_DEFAULT_GEOCODE_PID",
                "AMG_Y",
                "AMG_X",
                "DIRECTORY",
                "Deg Urban Name"], axis = 1, inplace = True)

final_data.head()

### Reset index

In [26]:
final_data.reset_index(inplace=True, drop= True)

###  Fill nulls in data identifier column

final_data["dataset_identifier"].fillna("Fixed Camera Data", inplace = True)
final_data.isnull().sum()

### Export final data

In [27]:
final_data.to_csv("/users/danielcorcoran/desktop/github_repos/tableau_projects/Vic Crash Stats (Extracted 4-5-2018)/raw data/viccrash_merged_fixed_cameras.csv", index_label= "viccrash_fixed_cameras_row_index")

In [28]:
final_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165076 entries, 0 to 165075
Data columns (total 60 columns):
ACCIDENTDATE                   164789 non-null object
ACCIDENTTIME                   164789 non-null object
ACCIDENT_NO                    164789 non-null object
ACCIDENT_ROW_INDEX             164789 non-null float64
ACCIDENT_TYPE                  164789 non-null float64
ADDRESS_DEFAULT_GEOCODE_PID    163912 non-null float64
ADDRESS_DETAIL_PID             163912 non-null object
ADDRESS_SITE_PID               163912 non-null float64
AMG_X                          163912 non-null float64
AMG_Y                          163912 non-null float64
Accident Type Desc             164789 non-null object
DAY_OF_WEEK                    164789 non-null float64
DCA Description                164789 non-null object
DCA_CODE                       164789 non-null float64
DIRECTORY                      163889 non-null object
Day Week Description           164789 non-null object
Deg Urban Name                 163912 non-null object
Distance                       163912 non-null float64
EDITION                        163889 non-null object
GNAF_PROPERTY_PID              141112 non-null float64
GRID_REFERENCE_X               163889 non-null object
GRID_REFERENCE_Y               163889 non-null object
Gindex                         163912 non-null float64
LGA_NAME                       163912 non-null object
LIGHT_CONDITION                164789 non-null float64
Lat                            164199 non-null float64
Lga Name All                   163912 non-null object
Light Condition Desc           164789 non-null object
Long                           164199 non-null float64
NODE_ID_x                      164789 non-null float64
NODE_ID_y                      163912 non-null float64
NODE_ROW_INDEX                 163912 non-null float64
NODE_TYPE                      163912 non-null object
NO_OF_VEHICLES                 164789 non-null float64
NO_PERSONS                     164789 non-null float64
NO_PERSONS_INJ_2               164789 non-null float64
NO_PERSONS_INJ_3               164789 non-null float64
NO_PERSONS_KILLED              164789 non-null float64
NO_PERSONS_NOT_INJ             164789 non-null float64
PAGE                           163889 non-null object
POLICE_ATTEND                  164789 non-null float64
POSTCODE                       163912 non-null float64
Postcode No                    163912 non-null float64
ROAD_GEOMETRY                  164789 non-null float64
ROW_INDEX                      163912 non-null float64
Region Name                    163912 non-null object
Road Geometry Desc             164789 non-null object
SEVERITY                       164789 non-null float64
SPEED_ZONE                     164789 non-null float64
STREET_LOCALITY_PID            163912 non-null object
STREET_NAME                    163912 non-null object
STREET_TYPE_CODE               162772 non-null object
camera_location_desc_long      287 non-null object
camera_location_desc_short     287 non-null object
dataset_identifier             165076 non-null object
lga_code                       164199 non-null float64
lga_name                       163912 non-null object
node_row_index                 163912 non-null float64
polygon_index                  163912 non-null float64
script_results                 163912 non-null object
dtypes: float64(33), object(27)
memory usage: 75.6+ MB